### ISSUE TITLE
Feature request: Ability to set a password for changing settings / disabling

### ISSUE THREAD

**Issue by Jython1415** [sdasda7777/ScheduleBlock#8]
I am considering using this extension, but before going through the set up process, I want to check if you support the option to have a password.

My use case is that I want someone to set the password, and I would have to go to them to disable the extension or change any of the settings.

**Comment by sdasda7777** [comment]
> I am considering using this extension, but before going through the set up process, I want to check if you support the option to have a password.

No, that is not the case.

> My use case is that I want someone to set the password, and I would have to go to them to disable the extension or change any of the settings.

This just not something you can do, as far as I know.

**Comment by Jython1415** [comment]
Thank you for the quick response.

Best of luck with your development work.
